# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\ci\containers\00002tlbheg\tmp\build\80754af9\rsync-recipes\console_shortcut_miniconda-0.1.1-on-winbuilder, last modified Tue Dec 20 16:36:46 2022
# ------------------------------------------------

package:
  name: console_shortcut_miniconda
  version: 0.1.1
build:
  number: '0'
  string: haa95532_0
requirements:
  build: []
  run:
    - python
  run_constrained:
    - anaconda-navigator >=1.9.8
app:
  entry: start cmd.exe /K "${CONDA_ROOT_PREFIX}\\Scripts\\activate.bat" "${CONDA_PREFIX}"
  summary: Anaconda Powershell Prompt
  type: desk
about:
  license: BSD-3-Clause
  license_family: BSD
  summary: Console shortcut creator for Windows (using menuinst)
extra:
  copy_test_source_files: true
  final: true
