# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# C:\b\abs_44a2d5ajjt\clone\recipe, last modified Fri Oct 28 06:59:38 2022
# ------------------------------------------------

package:
  name: conda-package-handling
  version: 1.9.0
source:
  sha256: 81e0771b8b10ab5c20678a5da714e36d97e321acfc3e5b304ec2e650ce84734b
  url: https://github.com/conda/conda-package-handling/archive/1.9.0.tar.gz
build:
  entry_points:
    - cph = conda_package_handling.cli:main
  number: '1'
  script: C:\\b\\abs_44a2d5ajjt\\croot\\conda-package-handling_1666940385350\\_h_env\\python.exe
    -m pip install . --no-deps -vv
  string: py310h8cc25b3_1
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - _libarchive_static_for_cph 3.6.1 h77ce953_0
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.10.11 haa95532_0
    - certifi 2022.9.24 py310haa95532_0
    - cython 0.29.32 py310hd77b12b_0
    - libffi 3.4.2 hd77b12b_4
    - lz4-c 1.9.3 h2bbff1b_1
    - openssl 1.1.1q h2bbff1b_0
    - pip 22.2.2 py310haa95532_0
    - python 3.10.6 hbb2ffb3_1
    - setuptools 63.4.1 py310haa95532_0
    - sqlite 3.39.3 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022e h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.6 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.2 h19a0ad4_0
  run:
    - python >=3.10,<3.11.0a0
    - tqdm
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pytest -v --cov=tests/ --cov-report=xml --color=yes tests/ -k "not test_secure_refusal_to_extract_abs_paths"
  imports:
    - conda_package_handling
    - conda_package_handling.archive_utils_cy
  requires:
    - mock
    - pytest
    - pytest-cov
    - pytest-mock
  source_files:
    - tests
about:
  description: 'cph is an abstraction of conda package handling and a tool for extracting,
    creating, and converting between formats.

    '
  dev_url: https://github.com/conda/conda-package-handling
  doc_url: https://github.com/conda/conda-package-handling/blob/main/README.md
  home: https://github.com/conda/conda-package-handling
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - static_deps_licenses/bzip2.txt
    - static_deps_licenses/libarchive.txt
    - static_deps_licenses/zlib.txt
    - static_deps_licenses/zstd.txt
  license_url: https://github.com/conda/conda-package-handling/blob/main/LICENSE
  summary: Create and extract conda packages of various formats
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 440a69bf-11d6-4b0b-93c9-2533844942e6
  recipe-maintainers:
    - beckermr
    - dbast
    - jezdez
    - msarahan
  remote_url: git@github.com:AnacondaRecipes/conda-package-handling-feedstock.git
  sha: 2c7e90bf5cbcfc088878afbf57d68c2782a92f35
