# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# C:\b\abs_36x9ifdcl4\clone\recipe, last modified Wed Oct 12 22:10:48 2022
# ------------------------------------------------

package:
  name: cryptography
  version: 38.0.1
source:
  sha256: 1db3d807a14931fa317f96435695d9ec386be7b84b618cc61cfa5d08b0ae33d7
  url: https://pypi.io/packages/source/c/cryptography/cryptography-38.0.1.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_36x9ifdcl4\\croot\\cryptography_1665612655344\\_h_env\\python.exe
    -m pip install . -vv
  string: py310h21b164f_0
requirements:
  build:
    - rust 1.56.0 haa95532_0
    - rust_win-64 1.46.0 hd77b12b_0
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.07.19 haa95532_0
    - certifi 2022.9.24 py310haa95532_0
    - cffi 1.15.1 py310h2bbff1b_0
    - libffi 3.4.2 hd77b12b_4
    - openssl 1.1.1q h2bbff1b_0
    - pip 22.2.2 py310haa95532_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.10.6 hbb2ffb3_0
    - semantic_version 2.8.5 pyhd3eb1b0_0
    - setuptools 63.4.1 py310haa95532_0
    - setuptools-rust 0.12.1 pyhd3eb1b0_0
    - sqlite 3.39.3 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tzdata 2022c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.6 h8cc25b3_0
    - zlib 1.2.12 h8cc25b3_3
  run:
    - cffi >=1.12
    - openssl
    - python >=3.10,<3.11.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - pytest -n auto
  imports:
    - cryptography
    - cryptography.fernet
    - cryptography.hazmat
    - cryptography.hazmat.backends
    - cryptography.hazmat.backends.openssl
    - cryptography.hazmat.bindings
    - cryptography.hazmat.bindings.openssl
    - cryptography.hazmat.primitives
    - cryptography.hazmat.primitives.asymmetric
    - cryptography.hazmat.primitives.ciphers
    - cryptography.hazmat.primitives.kdf
    - cryptography.hazmat.primitives.twofactor
    - cryptography.x509
  requires:
    - cryptography-vectors 38.0.1.*
    - hypothesis >=1.11.4,!=3.79.2
    - iso8601
    - pip
    - pretend
    - pytest >=6.2.0
    - pytest-benchmark
    - pytest-subtests
    - pytest-xdist
    - pytz
  source_files:
    - tests
about:
  description: 'Cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces to

    common cryptographic algorithms such as symmetric ciphers, message digests,

    and key derivation functions.

    '
  dev_url: https://github.com/pyca/cryptography
  doc_source_url: https://github.com/pyca/cryptography/blob/38.0.1/docs/index.rst
  doc_url: https://cryptography.io/en/38.0.1/
  home: https://github.com/pyca/cryptography
  license: (BSD-3-Clause OR Apache-2.0) AND PSF-2.0 AND MIT
  license_family: BSD
  license_file: LICENSE
  license_url: https://github.com/pyca/cryptography/blob/38.0.1/vectors/LICENSE
  summary: Provides cryptographic recipes and primitives to Python developers
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 364ce1c5-0fea-48be-8501-e1e968238d4a
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/cryptography-feedstock.git
  sha: 256a94b06cbc66b494341eb105a32e7f481bd531
