# This file created by conda-build 3.23.1
# meta.yaml template originally from:
# C:\b\abs_76_z92y5rh\clone\recipe, last modified Tue Nov 22 17:30:57 2022
# ------------------------------------------------

package:
  name: sqlite
  version: 3.40.0
source:
  patches:
    - expose_symbols.patch
  sha256: 0333552076d2700c75352256e91c78bf5cd62491589ba0c69aed0a81868980e7
  url: https://www.sqlite.org/2022/sqlite-autoconf-3400000.tar.gz
build:
  ignore_run_exports:
    - ncurses
  number: '0'
  run_exports:
    - sqlite >=3.40.0,<4.0a0
  string: h2bbff1b_0
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - sqlite3 --version
    - if not exist %PREFIX%\\Library\bin\sqlite3.dll exit 1
    - if not exist %PREFIX%\\Library\lib\sqlite3.lib exit 1
    - if not exist %PREFIX%\\Library\include\sqlite3.h exit 1
    - if not exist %PREFIX%\\Library\include\sqlite3ext.h exit 1
about:
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine. It is the most used database engine

    in the world.

    '
  dev_url: https://sqlite.org/src/dir?ci=trunk
  doc_source_url: https://sqlite.org/src/dir?ci=trunk&name=doc
  doc_url: https://www.sqlite.org/docs.html
  home: https://www.sqlite.org/
  license: blessing
  license_family: Other
  license_file: LICENSE.md
  license_url: https://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 76ef894f-659e-4958-9d3d-49c86a18f991
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - ocefpaf
    - snorfalorpagus
    - xylar
  remote_url: git@github.com:AnacondaRecipes/sqlite-feedstock.git
  sha: 7f81448b5e3de2fb0997a6aa0c52ccbf66eeb5f4
